version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: guetteluis/reverseproxy 
  backend_user:
    build:
      context: ../../restapi-user
    image: guetteluis/udagram-user
  backend_feed:
    build:
      context: ../../restapi-feed  
    image: guetteluis/udagram-feed
  frontend:
    build:
      context: ../../frontend  
    image: guetteluis/udagram-frontend
